`include"Master.v"
`include"Slave.v"
`include"APB4_MUX.v"
module APB_TOP#(parameter ADDR = 8, DATA_WIDTH = 8, ADDR_WIDTH = $clog2(ADDR),RAM_SIZE = 20) (
  input PCLK, PRESETn, transfer, READ_WRITE,   
  input [ADDR_WIDTH : 0] apb_write_paddr, apb_read_paddr,
  input [DATA_WIDTH -1 :0] apb_write_data, 
  output [DATA_WIDTH -1 :0]apb_read_data
);
  
  wire PSEL1, PENABLE, PWRITE;
  wire [ADDR_WIDTH : 0]PADDR;
  wire [DATA_WIDTH -1: 0]PWDATA; 
  wire [DATA_WIDTH -1: 0]PRDATA;
  wire PREADY;
  wire sel;
  wire SLV_PREADY0, SLV_PREADY1; 
  wire MST_PREADY;
  wire [DATA_WIDTH -1: 0]SLV_PRDATA0, SLV_PRDATA1; 
  wire SLV_PSEL0, SLV_PSEL1, MST_PRDATA;
  wire SLVERR0, SLVERR1, SLVERR;
  
  
  
  
  Master #(.ADDR(ADDR), .DATA_WIDTH(DATA_WIDTH), .ADDR_WIDTH(ADDR_WIDTH)) 
  M1(.PCLK(PCLK), .PRESETn(PRESETn), .transfer(transfer), .READ_WRITE(READ_WRITE), .PREADY(MST_PREADY), .apb_write_paddr(apb_write_paddr[ADDR_WIDTH-1:0]), .apb_read_paddr(apb_read_paddr[ADDR_WIDTH-1:0]), .apb_write_data(apb_write_data), .apb_read_data(apb_read_data), .PRDATA(PRDATA), .PSEL1(PSEL1), .PENABLE(PENABLE), .PWRITE(PWRITE),.PADDR(PADDR[ADDR_WIDTH-1:0]), .PWDATA(PWDATA), .SLVERR(SLVERR)
);
  
  ABP4_MUX #(.ADDR(ADDR), .DATA_WIDTH(DATA_WIDTH)) mux1
  (.sel(apb_write_paddr[ADDR_WIDTH] ), .MST_PSEL(PSEL1), .MST_PREADY(MST_PREADY), .SLV_PRDATA0(SLV_PRDATA0), .SLV_PRDATA1(SLV_PRDATA1), .SLV_PSEL0(SLV_PSEL0), .SLV_PSEL1(SLV_PSEL1), .MST_PRDATA(PRDATA), .SLV_PREADY0(SLV_PREADY0), .SLV_PREADY1(SLV_PREADY1), .SLVERR(SLVERR), .SLVERR0(SLVERR0), .SLVERR1(SLVERR1));
    
  slave #(.ADDR(ADDR), .DATA_WIDTH(DATA_WIDTH), .ADDR_WIDTH(ADDR_WIDTH), .RAM_SIZE(RAM_SIZE)) S0(
  .PCLK(PCLK), .PRESETn(PRESETn), .PSEL1(SLV_PSEL0), .PENABLE(PENABLE), .PWRITE(PWRITE), .PADDR(PADDR[ADDR_WIDTH-1 : 0]), .PWDATA(PWDATA),.PRDATA(SLV_PRDATA0),.PREADY(SLV_PREADY0), .PSLVERR(SLVERR0)
);
  
  slave #(.ADDR(ADDR), .DATA_WIDTH(DATA_WIDTH), .ADDR_WIDTH(ADDR_WIDTH), .RAM_SIZE(RAM_SIZE)) S1(
    .PCLK(PCLK), .PRESETn(PRESETn), .PSEL1(SLV_PSEL1), .PENABLE(PENABLE), .PWRITE(PWRITE), .PADDR(PADDR[ADDR_WIDTH-1 : 0]), .PWDATA(PWDATA),.PRDATA(SLV_PRDATA1),.PREADY(SLV_PREADY1), .PSLVERR(SLVERR1)
);

endmodule
